### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Tentacionboi** [kentonson/bob-plugin-groq-translate#1]
你好，下载是一个文件夹，无法更新安装

**Comment by kentonson** [comment]
好的，今晚更新

**Comment by kongds1999** [comment]
@Tentacionboi 新的release已提交，你可以直接在软件插件列表检查更新：
<img width="925" alt="image" src="https://github.com/kentonson/bob-plugin-groq-translate/assets/110104533/5858aa22-4c1e-4d28-a7bc-6934441d7576">
也可以从[v0.3.0](https://github.com/kentonson/bob-plugin-groq-translate/releases/download/v0.3.0/bob-plugin-groq-translate-v0.3.0.bobplugin)下载插件并安装使用
