### ISSUE TITLE
能否提供类似用户自定义的文本

### ISSUE THREAD

**Issue by caisxg** [kentonson/bob-plugin-groq-translate#2]
希望能够[bob-plugin-openai-translator](https://github.com/openai-translator/bob-plugin-openai-translator) 像 这个一样, 提供用户的命令.  虽然作者也提供了相应的命令, 但是不太明白, 

<img width="382" alt="图片" src="https://github.com/kentonson/bob-plugin-groq-translate/assets/134250472/73eaa938-285c-4704-8cb6-9605f1c17076">

类似希望有这样的接口,供用户选择

<img width="450" alt="图片" src="https://github.com/kentonson/bob-plugin-groq-translate/assets/134250472/cc02e9e0-13fb-4ca2-9a4e-c56f3dd3c4d2">

**Comment by caisxg** [comment]
贴一个返回乱码的图, 不知道啥原因

<img width="416" alt="图片" src="https://github.com/kentonson/bob-plugin-groq-translate/assets/134250472/c0cf74d1-6fb5-4081-ab2c-f7c7133a101d">

**Comment by kongds1999** [comment]
@caisxg 感谢提议，有这个计划可以自定义prompt，关于下面这个问题，目前的猜测是llama3的缘故，这个模型目前应该是对中文的回复不是很好，正常对话也经常会有中英文穿插回复等情况，可能要等五一假期结束啦
